const data = [
    {
        "lat": 10.8203192,
        "lng": 106.7074485,
        "projectName": "Thu Duc Planning Platform",
        "country": "Vietnam",
        "location": "Thu Duc City",
        "startDate": "Nov 2022",
        "completionDate": "Apr 2023",
        "partner": "",
        "client": "Thu Duc City",
        "clientType": "Government",
        "description": "A data-driven web GIS dasboard for comparing existing and proposed land use plans.",
        "projectValue": 30000,
        "projectScale": 22000,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "GIS",
        "photo1": "https://raw.githubusercontent.com/cmlosariaGIS/enCityProjects/main/Projects/01_Thu%20Duc%20City%20GIS%20Planning%20Platform/Images/Picture1.jpg",
        "photo2": "https://raw.githubusercontent.com/cmlosariaGIS/enCityProjects/main/Projects/01_Thu%20Duc%20City%20GIS%20Planning%20Platform/Images/Picture2.JPG",
        "attachment": "https://raw.githubusercontent.com/cmlosariaGIS/enCityProjects/main/Projects/01_Thu%20Duc%20City%20GIS%20Planning%20Platform/Project%20Sheet/SAMPLE%20PROJECT%20SHEET.pdf"
    },
    {
        "lat": -6.836791,
        "lng": 107.928307,
        "projectName": "Butom Industrial Area",
        "country": "Indonesia",
        "location": "Sumedang Regency",
        "startDate": "Jan 1970",
        "completionDate": "Jan 1970",
        "partner": "",
        "client": "",
        "clientType": "Government",
        "description": "A green and integrated industrial township.",
        "projectValue": 10000,
        "projectScale": 4000,
        "status": "Completed",
        "sector1": "Industrial",
        "sector2": "Urban Planning",
        "photo1": "https://encity.co/wp-content/uploads/2024/01/Residential-2048x1484.jpeg",
        "photo2": "https://encity.co/wp-content/uploads/2024/01/Industrial-2048x1344.jpeg",
        "attachment": ""
    },
    {
        "lat": 1.431829,
        "lng": 103.71842,
        "projectName": "Lim Chu Kang Agri-food Production Hub",
        "country": "Singapore",
        "location": "Lim Chu Kang",
        "startDate": "Jan 1970",
        "completionDate": "Jan 1970",
        "partner": "Sasaki, Meinhardt, Agritecture, BioSea",
        "client": "",
        "clientType": "Government",
        "description": "We envision Lim Chu Kang Agri-Food Production Hub being divided into three zones to create a balanced and vibrant mix of programs with distinct characters.",
        "projectValue": 18000,
        "projectScale": 390,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "Architecture",
        "photo1": "https://encity.co/wp-content/uploads/2023/06/LCK_img_4.jpg",
        "photo2": "https://encity.co/wp-content/uploads/2023/06/LCK_img_7-2048x1116.jpg",
        "attachment": ""
    },
    {
        "lat": 12.25522,
        "lng": 109.196053,
        "projectName": "Khanh Hoa Provincial Government Centre",
        "country": "Vietnam",
        "location": "Nha Trang City",
        "startDate": "Jan 1970",
        "completionDate": "Jan 1970",
        "partner": "",
        "client": "Khanh Hoa Provincial Government ",
        "clientType": "Government",
        "description": "The Khanh Hoa Provincial Government Centre will be a contemporary icon for the province, anchored in cultural traditions and headed towards progress. ",
        "projectValue": 50000,
        "projectScale": 0.5,
        "status": "Completed",
        "sector1": "Architecture",
        "sector2": "Urban Planning",
        "photo1": "https://encity.co/wp-content/uploads/2023/10/khanh-hoa-FINAL-7-2-copy.jpg",
        "photo2": "https://encity.co/wp-content/uploads/2023/10/khanh-hoa-FINAL-1-copy.jpg",
        "attachment": ""
    }
];

// Add more Project data rows as needed
