const data = [
    {
        "lat": 10.8203192,
        "lng": 106.7074485,
        "projectName": "Thu Duc Planning Platform",
        "country": "Vietnam",
        "location": "Thu Duc City",
        "startDate": "Nov 2022",
        "completionDate": "Apr 2023",
        "partner": "",
        "client": "Thu Duc City",
        "clientType": "Government",
        "description": "A data-driven web GIS dasboard for comparing existing and proposed land use plans.",
        "projectValue": "",
        "projectScale": 22000,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "GIS",
        "photo1": "https://raw.githubusercontent.com/cmlosariaGIS/enCityProjects/main/Projects/01_Thu%20Duc%20City%20GIS%20Planning%20Platform/Images/Picture1.jpg",
        "photo2": "https://raw.githubusercontent.com/cmlosariaGIS/enCityProjects/main/Projects/01_Thu%20Duc%20City%20GIS%20Planning%20Platform/Images/Picture2.JPG",
        "attachment": "https://raw.githubusercontent.com/cmlosariaGIS/enCityProjects/main/Projects/01_Thu%20Duc%20City%20GIS%20Planning%20Platform/Project%20Sheet/SAMPLE%20PROJECT%20SHEET.pdf"
    },
    {
        "lat": -6.836791,
        "lng": 107.928307,
        "projectName": "Butom Industrial Park",
        "country": "Indonesia",
        "location": "Sumedang",
        "startDate": "2023",
        "completionDate": "",
        "partner": "",
        "client": "West Java Government",
        "clientType": "Private",
        "description": "A green and integrated industrial township.",
        "projectValue": "",
        "projectScale": "",
        "status": "Completed",
        "sector1": "Business Park/High-tech Park/Industrial Park Planning",
        "sector2": "Urban Planning",
        "photo1": "https://encity.co/wp-content/uploads/2024/01/Residential-2048x1484.jpeg",
        "photo2": "https://encity.co/wp-content/uploads/2024/01/Industrial-2048x1344.jpeg",
        "attachment": "https://raw.githubusercontent.com/cmlosariaGIS/enCityProjects/main/Projects/Project%20Sheet_Butom%20Industrial%20Area.pdf"
    },
    {
        "lat": 1.431829,
        "lng": 103.71842,
        "projectName": "Lim Chu Kang Agri-food Production Hub",
        "country": "Singapore",
        "location": "Lim Chu Kang",
        "startDate": "2019",
        "completionDate": "2020",
        "partner": "Sasaki, Meinhardt, Agritecture, BioSea",
        "client": "",
        "clientType": "Government",
        "description": "We envision Lim Chu Kang Agri-Food Production Hub being divided into three zones to create a balanced and vibrant mix of programs with distinct characters.",
        "projectValue": "",
        "projectScale": 390,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "Architecture",
        "photo1": "https://encity.co/wp-content/uploads/2023/06/LCK_img_4.jpg",
        "photo2": "https://encity.co/wp-content/uploads/2023/06/LCK_img_7-2048x1116.jpg",
        "attachment": "https://raw.githubusercontent.com/cmlosariaGIS/enCityProjects/main/Projects/Project%20Sheet_Lim%20Chu%20Kang%20Agri-food%20Production%20Hub.pdf"
    },
    {
        "lat": 12.25522,
        "lng": 109.196053,
        "projectName": "Khanh Hoa Provincial Government Centre",
        "country": "Vietnam",
        "location": "Nha Trang City",
        "startDate": "2023",
        "completionDate": "2023",
        "partner": "",
        "client": "Khanh Hoa Provincial Government ",
        "clientType": "Government",
        "description": "The Khanh Hoa Provincial Government Centre will be a contemporary icon for the province, anchored in cultural traditions and headed towards progress. ",
        "projectValue": "",
        "projectScale": 0.5,
        "status": "Completed",
        "sector1": "Building Architecture",
        "sector2": "Urban Planning",
        "photo1": "https://encity.co/wp-content/uploads/2023/10/khanh-hoa-FINAL-7-2-copy.jpg",
        "photo2": "https://encity.co/wp-content/uploads/2023/10/khanh-hoa-FINAL-1-copy.jpg",
        "attachment": "https://raw.githubusercontent.com/cmlosariaGIS/enCityProjects/main/Projects/Project%20Sheet_Khanh%20Hoa%20Provincial%20Government%20Centre.pdf"
    },
    {
        "lat": 10.873737,
        "lng": 106.819898,
        "projectName": "GS Metro Long Binh Mixed-use Community",
        "country": "Vietnam",
        "location": "Thu Duc City",
        "startDate": "2022",
        "completionDate": "2024",
        "partner": "Sasaki",
        "client": "Vietnam GS Enterprise LLC",
        "clientType": "Private",
        "description": "This master plan aims to fully unlock the site’s potential, leveraging the unique physical and environmental conditions of the site, to develop an integrated, inclusive and inspirational urban community hub for the upper east side of Thu Duc City. ",
        "projectValue": "",
        "projectScale": 54,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "Sustainable Development",
        "photo1": "https://encity.co/wp-content/uploads/2023/11/GS-Aerial_01_1-copy.jpg",
        "photo2": "https://encity.co/wp-content/uploads/2023/11/z4860870015439_2e526ee6920024c2be2b673f5d3dde98-e1699437288790.jpg",
        "attachment": "https://raw.githubusercontent.com/cmlosariaGIS/enCityProjects/main/Projects/Project%20Sheet_GS%20Metro%20Long%20Binh%20Mixed-use%20Community.pdf"
    },
    {
        "lat": -6.296316,
        "lng": 106.821843,
        "projectName": "TOD-led Urban Regeneration for South Jakarta",
        "country": "Indonesia",
        "location": "South Jakarta",
        "startDate": "2023",
        "completionDate": "2024",
        "partner": "PWD, JPI",
        "client": "",
        "clientType": "Government",
        "description": "Ragunan 2045 will be resilient, inclusive & kampung-inspired. It will add to the restoration of quality living for Jakartans, allowing all residents of various income levels to enjoy quality amenities and public space, with equitable access to housing options and a chance to create community.",
        "projectValue": "",
        "projectScale": 29,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "Transportation",
        "photo1": "https://encity.co/wp-content/uploads/2023/11/photo_2023-11-10_14-33-21-1.jpg",
        "photo2": "https://encity.co/wp-content/uploads/2023/11/231031_Jakarta-2045_TOD-Forum-2-1-2048x1154.jpg",
        "attachment": "https://raw.githubusercontent.com/cmlosariaGIS/enCityProjects/main/Projects/Project%20Sheet_TOD-led%20Urban%20Regeneration%20for%20South%20Jakarta.pdf"
    },
    {
        "lat": 15.881294,
        "lng": 108.376996,
        "projectName": "Casamia Balanca Hoi An Waterfront Eco-community",
        "country": "Vietnam",
        "location": "Hoi An",
        "startDate": "2019",
        "completionDate": "2020",
        "partner": "",
        "client": "",
        "clientType": "Government",
        "description": "A waterfront destination for both tourists and the local community, with nightlife and lifestyle attractions.",
        "projectValue": "",
        "projectScale": 30,
        "status": "Completed",
        "sector1": "Heritage Preservation",
        "sector2": "Sustainable Development",
        "photo1": "https://encity.co/wp-content/uploads/2022/06/FuturArc-Hoi-An-Website-4-Hoi-An-Waterfront_VTN-Architects-1.jpg",
        "photo2": "https://encity.co/wp-content/uploads/2022/07/363502392_1005919210850496_8589311349754184039_n-e1690448105228.png",
        "attachment": "https://raw.githubusercontent.com/cmlosariaGIS/enCityProjects/main/Projects/Project%20Sheet_Casamia%20Balanca%20Hoi%20An%20Waterfront%20Eco-community.pdf"
    },
    {
        "lat": 17.399885,
        "lng": 102.797387,
        "projectName": "Viet Nam town - Udon Thani",
        "country": "Thailand",
        "location": "Udon Thani",
        "startDate": "2023",
        "completionDate": "",
        "partner": "",
        "client": "Commitee for Overseas Vietnamese",
        "clientType": "Government",
        "description": "",
        "projectValue": "",
        "projectScale": "",
        "status": "",
        "sector1": "Urban Planning",
        "sector2": "Landscape Architecture and Urban Design",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 4.174223,
        "lng": 73.509541,
        "projectName": "Maldives Urban Agriculture",
        "country": "Maldives",
        "location": "Maldives",
        "startDate": "2023",
        "completionDate": "",
        "partner": "",
        "client": "ADB",
        "clientType": "ODA, Financial Instutions",
        "description": "",
        "projectValue": "",
        "projectScale": 42.3,
        "status": "",
        "sector1": "Agriculture",
        "sector2": "Capability building",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 21.577058,
        "lng": 105.700773,
        "projectName": "Nui Coc Lake",
        "country": "Vietnam",
        "location": "Thai Nguyen",
        "startDate": "27-Apr-2021",
        "completionDate": "",
        "partner": "",
        "client": "TNG",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": "",
        "status": "Completed",
        "sector1": "Regional and Provincial Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Van Giang Admin Center",
        "country": "Vietnam",
        "location": "Hung Yen",
        "startDate": "28-Jun-2018",
        "completionDate": "",
        "partner": "",
        "client": "Glopan",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 10,
        "status": "Completed",
        "sector1": "Urban Conservation and Redevelopment",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Con Tien Township",
        "country": "Vietnam",
        "location": "Quang Nam",
        "startDate": "3-Jul-2018",
        "completionDate": "",
        "partner": "",
        "client": "Dat Phuong",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 31.3,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Nam Phu Yen PK 1&2",
        "country": "Vietnam",
        "location": "Phu Yen",
        "startDate": "8-Aug-2018",
        "completionDate": "",
        "partner": "",
        "client": "TDH Ecoland",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 251,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Thuy Duong Golf Township",
        "country": "Vietnam",
        "location": "Hue",
        "startDate": "9-Aug-2018",
        "completionDate": "",
        "partner": "",
        "client": "TDH Ecoland",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 439,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Phu Yen PK5",
        "country": "Vietnam",
        "location": "Phu Yen",
        "startDate": "8-Oct-2018",
        "completionDate": "",
        "partner": "",
        "client": "TDH Ecoland",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 64.5,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Vung Tau Nui Lon Nui Nho",
        "country": "Vietnam",
        "location": "Vung Tau",
        "startDate": "25-Oct-2018",
        "completionDate": "",
        "partner": "",
        "client": "TDH Ecoland",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 780,
        "status": "Completed",
        "sector1": "Urban Conservation and Redevelopment",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Nam Song Ba Eco Township PK 4",
        "country": "Vietnam",
        "location": "Phu Yen",
        "startDate": "12-Nov-2018",
        "completionDate": "",
        "partner": "",
        "client": "TDH Ecoland",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 500,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Lang Chai Resort",
        "country": "Vietnam",
        "location": "HCMC",
        "startDate": "13-Dec-2018",
        "completionDate": "",
        "partner": "",
        "client": "Hoa Lam",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 13.35,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 11.593584,
        "lng": 108.982514,
        "projectName": "Phan Rang Township",
        "country": "Vietnam",
        "location": "Ninh Thuan",
        "startDate": "5-Dec-2018",
        "completionDate": "",
        "partner": "",
        "client": "TDH Ecoland",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 72,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Prenn Lake Eco Tourism Township",
        "country": "Vietnam",
        "location": "Lam Dong",
        "startDate": "10-Dec-2018",
        "completionDate": "",
        "partner": "",
        "client": "TDH Ecoland",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 72,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Van Lang University",
        "country": "Vietnam",
        "location": "Hanoi",
        "startDate": "2-Mar-2019",
        "completionDate": "",
        "partner": "",
        "client": "Capella",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 1000,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "Landscape Architecture and Urban Design",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 11.751197,
        "lng": 106.895965,
        "projectName": "Binh Phuoc masterplan",
        "country": "Vietnam",
        "location": "Binh Phuoc",
        "startDate": "15-Jan-2019",
        "completionDate": "",
        "partner": "",
        "client": "Becamex IDC",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 5.8,
        "status": "Completed",
        "sector1": "Architectural and Landscape Design",
        "sector2": "Business Park/High-tech Park/Industrial Park Planning",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Hue Zone E",
        "country": "Vietnam",
        "location": "Hue",
        "startDate": "28-Feb-2019",
        "completionDate": "",
        "partner": "",
        "client": "TDH Ecoland",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": "",
        "status": "Completed",
        "sector1": "Business Park/High-tech Park/Industrial Park Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 21.563631,
        "lng": 107.889683,
        "projectName": "Mong Cai",
        "country": "Vietnam",
        "location": "Quang Ninh",
        "startDate": "6-Mar-2019",
        "completionDate": "",
        "partner": "",
        "client": "TDH Ecoland",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 670,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Nguyen Hoang",
        "country": "Vietnam",
        "location": "Lam Dong",
        "startDate": "11-Mar-2019",
        "completionDate": "",
        "partner": "",
        "client": "TDH Ecoland",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 320,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 20.844486,
        "lng": 106.699604,
        "projectName": "Hai Phong General Master Plan",
        "country": "Vietnam",
        "location": "Hai Phong",
        "startDate": "22-Nov-2019",
        "completionDate": "",
        "partner": "",
        "client": "Hai Phong Department of Construction",
        "clientType": "Government",
        "description": "",
        "projectValue": "",
        "projectScale": 320,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "City Master Planning",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Long An Site 2",
        "country": "Vietnam",
        "location": "Long An",
        "startDate": "28-Jun-2019",
        "completionDate": "",
        "partner": "",
        "client": "TDH Ecoland",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 184,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Ecoland 1 - Ben Luc",
        "country": "Vietnam",
        "location": "Long An",
        "startDate": "23-May-2019",
        "completionDate": "",
        "partner": "",
        "client": "TDH Ecoland",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 184,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 21.311624,
        "lng": 105.596047,
        "projectName": "North Vinh Yen",
        "country": "Vietnam",
        "location": "Vinh Yen",
        "startDate": "27-Jun-2019",
        "completionDate": "",
        "partner": "",
        "client": "TDH Ecoland",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": "",
        "status": "Completed",
        "sector1": "Regional and Provincial Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 15.873203,
        "lng": 108.334481,
        "projectName": "South Hoi An",
        "country": "Vietnam",
        "location": "Quang Nam",
        "startDate": "15-Jul-2019",
        "completionDate": "",
        "partner": "",
        "client": "Dat Phuong",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 1200,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "ShangriLa Hightech Park",
        "country": "",
        "location": "HCMC",
        "startDate": "15-Nov-2019",
        "completionDate": "",
        "partner": "",
        "client": "Hoa Lam",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 187,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Long An VSIP",
        "country": "Vietnam",
        "location": "Long An",
        "startDate": "27-Mar-2019",
        "completionDate": "",
        "partner": "",
        "client": "Becamex IDC",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 187,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "Business Park/High-tech Park/Industrial Park Planning",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 10.240939,
        "lng": 106.377611,
        "projectName": "Ben Tre Strategic Development Vision",
        "country": "Vietnam",
        "location": "Ben Tre",
        "startDate": "20-Jun-2019",
        "completionDate": "",
        "partner": "",
        "client": "RB",
        "clientType": "Government",
        "description": "",
        "projectValue": "",
        "projectScale": 101,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "Regional and Provincial Planning",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 10.840308,
        "lng": 106.683059,
        "projectName": "Go Vap Cultural Park",
        "country": "Vietnam",
        "location": "HCMC",
        "startDate": "",
        "completionDate": "",
        "partner": "",
        "client": "Hoa Lam",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 184,
        "status": "Completed",
        "sector1": "Infrastructure Planning/Design",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 10.037938,
        "lng": 105.755148,
        "projectName": "Can Tho",
        "country": "Vietnam",
        "location": "Can Tho",
        "startDate": "6-Sep-2019",
        "completionDate": "",
        "partner": "",
        "client": "Hoa Lam",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": "N/A",
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Hai Duong Zone 3.4.5",
        "country": "Vietnam",
        "location": "Hai Duong",
        "startDate": "6-Aug-2019",
        "completionDate": "",
        "partner": "",
        "client": "TDH Ecoland",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 3000,
        "status": "Completed",
        "sector1": "Business Park/High-tech Park/Industrial Park Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Hai Duong Sport Town",
        "country": "Vietnam",
        "location": "Hai Duong",
        "startDate": "7-Aug-2019",
        "completionDate": "",
        "partner": "",
        "client": "TDH Ecoland",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": "",
        "status": "Completed",
        "sector1": "Regional and Provincial Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Go Cat Eco-community",
        "country": "Vietnam",
        "location": "HCMC",
        "startDate": "15-Oct-2019",
        "completionDate": "",
        "partner": "",
        "client": "TDH Ecoland",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 37,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Binh Duong STIP Bau Bang",
        "country": "Vietnam",
        "location": "Binh Duong",
        "startDate": "2-May-2019",
        "completionDate": "",
        "partner": "",
        "client": "Becamex IDC",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 7.89,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "Business Park/High-tech Park/Industrial Park Planning",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Southi Duong Township 1/2000",
        "country": "Vietnam",
        "location": "Hai Duong",
        "startDate": "9-Dec-2019",
        "completionDate": "",
        "partner": "",
        "client": "TDH Ecoland",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 303,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "HD Multi Functional Service Center",
        "country": "Vietnam",
        "location": "Hai Duong",
        "startDate": "12-Feb-2020",
        "completionDate": "",
        "partner": "",
        "client": "TDH Ecoland",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 334,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "Landscape Architecture and Urban Design",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "iNha Trang",
        "country": "Vietnam",
        "location": "Khanh Hoa",
        "startDate": "28-Feb-2020",
        "completionDate": "",
        "partner": "",
        "client": "ATC",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": "",
        "status": "Completed",
        "sector1": "Business Park/High-tech Park/Industrial Park Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Cua Lap Vung Tau",
        "country": "Vietnam",
        "location": "Vung Tau",
        "startDate": "19-Mar-2020",
        "completionDate": "",
        "partner": "",
        "client": "TDH Ecoland",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 38,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 18.697478,
        "lng": 105.678428,
        "projectName": "Vinh Township",
        "country": "Vietnam",
        "location": "Nghe An",
        "startDate": "19-Mar-2020",
        "completionDate": "",
        "partner": "",
        "client": "TDH Ecoland",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 1039,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Hoc Mon Eco-Community",
        "country": "Vietnam",
        "location": "HCMC",
        "startDate": "9-Dec-2019",
        "completionDate": "",
        "partner": "",
        "client": "Hoa Lam",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 242,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Hai Cai Chien",
        "country": "Vietnam",
        "location": "Quang Ninh",
        "startDate": "1-Jul-2020",
        "completionDate": "",
        "partner": "",
        "client": "BTH (Ben Thanh Holding)",
        "clientType": "Government",
        "description": "",
        "projectValue": "",
        "projectScale": "6.500m2",
        "status": "Completed",
        "sector1": "Architectural and Landscape Design",
        "sector2": "Regional and Provincial Planning",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 22.338352,
        "lng": 103.83967,
        "projectName": "Sapa Eco-Tourism Township",
        "country": "Vietnam",
        "location": "Lao Cai",
        "startDate": "6-Jul-2020",
        "completionDate": "",
        "partner": "",
        "client": "TDH Ecoland",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 2159,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Linh Trung Residence",
        "country": "Vietnam",
        "location": "HCMC",
        "startDate": "7-Sep-2020",
        "completionDate": "",
        "partner": "",
        "client": "Hado",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 126,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "Landscape Architecture and Urban Design",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Binh Thuan VSIP",
        "country": "Vietnam",
        "location": "Binh Thuan",
        "startDate": "15-May-2020",
        "completionDate": "",
        "partner": "",
        "client": "Becamex IDC",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 210,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "Business Park/High-tech Park/Industrial Park Planning",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Binh Tan 4.5ha",
        "country": "Vietnam",
        "location": "Binh Tan",
        "startDate": "17-Aug-2020",
        "completionDate": "",
        "partner": "",
        "client": "Hoa Lam",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 46.65,
        "status": "Completed",
        "sector1": "Urban Conservation and Redevelopment",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "HIID",
        "country": "Vietnam",
        "location": "HCMC",
        "startDate": "16-Sep-2020",
        "completionDate": "",
        "partner": "",
        "client": "Ho Chi Minh DPA",
        "clientType": "Government",
        "description": "",
        "projectValue": "",
        "projectScale": 24000,
        "status": "Completed",
        "sector1": "Regional and Provincial Planning",
        "sector2": "City Master Planning",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Hung Hoa - Vinh",
        "country": "Vietnam",
        "location": "Nghe An",
        "startDate": "7-Sep-2020",
        "completionDate": "",
        "partner": "",
        "client": "TDH Ecoland",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 270,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Golf Ecopark",
        "country": "Vietnam",
        "location": "Hung Yen",
        "startDate": "5-Oct-2020",
        "completionDate": "",
        "partner": "",
        "client": "Ecopark",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 27.1,
        "status": "Completed",
        "sector1": "Landscape Architecture and Urban Design",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Ha Long Xanh",
        "country": "Vietnam",
        "location": "Quảng Ninh",
        "startDate": "17-Dec-2020",
        "completionDate": "",
        "partner": "",
        "client": "VinHome",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 6981,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Kallang - Kolam Ayer",
        "country": "Singapore",
        "location": "Singapore",
        "startDate": "25-Aug-2020",
        "completionDate": "",
        "partner": "",
        "client": "JTC",
        "clientType": "Government",
        "description": "",
        "projectValue": "",
        "projectScale": 4.5,
        "status": "Completed",
        "sector1": "Urban Conservation and Redevelopment",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Hue Colliers",
        "country": "Vietnam",
        "location": "Hue",
        "startDate": "14-Sep-2020",
        "completionDate": "",
        "partner": "",
        "client": "Atkins COLLIERS",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 21000,
        "status": "Completed",
        "sector1": "Regional and Provincial Planning",
        "sector2": "Research",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Synergy",
        "country": "Vietnam",
        "location": "Dong Nai",
        "startDate": "21-Jan-2021",
        "completionDate": "",
        "partner": "",
        "client": "Capitaland",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 200,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "Business Park/High-tech Park/Industrial Park Planning",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Ecopark CBD",
        "country": "Vietnam",
        "location": "Hung Yen",
        "startDate": "25-Jan-2021",
        "completionDate": "",
        "partner": "",
        "client": "Ecopark",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 800,
        "status": "Completed",
        "sector1": "Research",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Binh Phuoc provincial planning",
        "country": "Vietnam",
        "location": "Binh Phuoc",
        "startDate": "8-Jan-2021",
        "completionDate": "",
        "partner": "",
        "client": "Binh Phuoc DPI",
        "clientType": "Government",
        "description": "",
        "projectValue": "",
        "projectScale": 61.5,
        "status": "Completed",
        "sector1": "Urban Conservation and Redevelopment",
        "sector2": "Regional and Provincial Planning",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Kim Boi Master Plan",
        "country": "Vietnam",
        "location": "Hoa Binh",
        "startDate": "19-Feb-2021",
        "completionDate": "",
        "partner": "",
        "client": "VinHome",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 111.2,
        "status": "Completed",
        "sector1": "Urban Conservation and Redevelopment",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "NEO",
        "country": "Vietnam",
        "location": "Bac Giang",
        "startDate": "22-Feb-2021",
        "completionDate": "",
        "partner": "",
        "client": "Capitaland",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": "",
        "status": "Completed",
        "sector1": "",
        "sector2": "Business Park/High-tech Park/Industrial Park Planning",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Hoa Khanh Nam",
        "country": "Vietnam",
        "location": "Da Nang",
        "startDate": "12-Apr-2021",
        "completionDate": "",
        "partner": "",
        "client": "TDH Ecoland",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": "",
        "status": "Completed",
        "sector1": "",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Lien Chieu District",
        "country": "Vietnam",
        "location": "Da Nang",
        "startDate": "13-Apr-2021",
        "completionDate": "",
        "partner": "",
        "client": "TDH Ecoland",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 2780,
        "status": "Completed",
        "sector1": "Urban Conservation and Redevelopment",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Tay Ninh Provincial Planning",
        "country": "Vietnam",
        "location": "Tay Ninh",
        "startDate": "20-Apr-2021",
        "completionDate": "",
        "partner": "",
        "client": "Tay Ninh DPI",
        "clientType": "Government",
        "description": "",
        "projectValue": "",
        "projectScale": 416,
        "status": "Completed",
        "sector1": "Business Park/High-tech Park/Industrial Park Planning",
        "sector2": "Regional and Provincial Planning",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Buon Ma Thuot",
        "country": "Vietnam",
        "location": "Buon Ma Thuot",
        "startDate": "23-Apr-2021",
        "completionDate": "",
        "partner": "",
        "client": "TDH Ecoland",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": "",
        "status": "Completed",
        "sector1": "Regional and Provincial Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Vinh Phuc Hightech",
        "country": "Vietnam",
        "location": "Vinh Phuc",
        "startDate": "11-May-2021",
        "completionDate": "",
        "partner": "",
        "client": "TDH Ecoland",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 30,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Dieu Tri Binh Dinh",
        "country": "Vietnam",
        "location": "Binh Dinh",
        "startDate": "6-May-2021",
        "completionDate": "",
        "partner": "",
        "client": "Capital House",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 190,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Hon Mot Island",
        "country": "Vietnam",
        "location": "Phu Quoc",
        "startDate": "18-May-2021",
        "completionDate": "",
        "partner": "",
        "client": "VinHome",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 1386,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "CBD& Golfcourse - concept",
        "country": "Vietnam",
        "location": "Hung Yen",
        "startDate": "11-May-2021",
        "completionDate": "",
        "partner": "",
        "client": "Ecopark",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 1072,
        "status": "Completed",
        "sector1": "Business Park/High-tech Park/Industrial Park Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "CBD& Golfcourse - submission",
        "country": "Vietnam",
        "location": "Hung Yen",
        "startDate": "11-May-2021",
        "completionDate": "",
        "partner": "",
        "client": "Ecopark",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 45,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Quang Ngai Master Plan",
        "country": "Vietnam",
        "location": "Quang Ngai",
        "startDate": "1-Jun-2021",
        "completionDate": "",
        "partner": "",
        "client": "SunGroup",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 499.07,
        "status": "Completed",
        "sector1": "Urban Conservation and Redevelopment",
        "sector2": "Research",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Heritage Study",
        "country": "Singapore",
        "location": "Singapore",
        "startDate": "17-Jun-2021",
        "completionDate": "",
        "partner": "",
        "client": "NUS",
        "clientType": "Government",
        "description": "",
        "projectValue": "",
        "projectScale": "",
        "status": "Completed",
        "sector1": "Regional and Provincial Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Vong Nhi township",
        "country": "Vietnam",
        "location": "Quang Nam",
        "startDate": "21-Jun-2021",
        "completionDate": "",
        "partner": "",
        "client": "Dat Phuong",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": "",
        "status": "Completed",
        "sector1": "",
        "sector2": "Landscape Architecture and Urban Design",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 11.963045,
        "lng": 108.391868,
        "projectName": "Cam Ly township",
        "country": "Vietnam",
        "location": "Lam Dong",
        "startDate": "2-Aug-2021",
        "completionDate": "",
        "partner": "",
        "client": "TDH Ecoland",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 32,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "Landscape Architecture and Urban Design",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 21.116448,
        "lng": 106.030097,
        "projectName": "Tien Du",
        "country": "Vietnam",
        "location": "Bac Ninh",
        "startDate": "16-Aug-2021",
        "completionDate": "",
        "partner": "",
        "client": "Xuan Cau",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 54,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Tam Xa",
        "country": "Vietnam",
        "location": "Hanoi",
        "startDate": "18-Aug-2021",
        "completionDate": "",
        "partner": "",
        "client": "Xuan Cau",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 120,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Tam Xa - VO 1",
        "country": "Vietnam",
        "location": "Hanoi",
        "startDate": "10-Jun-2022",
        "completionDate": "",
        "partner": "",
        "client": "Xuan Cau",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 318,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Da Nang Waterfront Bay",
        "country": "Vietnam",
        "location": "Da Nang",
        "startDate": "24-Aug-2021",
        "completionDate": "",
        "partner": "",
        "client": "TDH Ecoland",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 1530,
        "status": "Completed",
        "sector1": "",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Aeropolis Can Tho",
        "country": "Vietnam",
        "location": "Can Tho",
        "startDate": "13-Oct-2021",
        "completionDate": "",
        "partner": "",
        "client": "Phu Long",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 1645,
        "status": "Completed",
        "sector1": "Business Park/High-tech Park/Industrial Park Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 11.745845,
        "lng": 108.428647,
        "projectName": "Da Nhim river",
        "country": "Vietnam",
        "location": "Lam Dong",
        "startDate": "30-Oct-2021",
        "completionDate": "",
        "partner": "",
        "client": "Hung Ngan",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 220,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 12.029345,
        "lng": 108.9626434,
        "projectName": "Khanh Son Eco-township",
        "country": "Vietnam",
        "location": "Khanh Hoa",
        "startDate": "1-Nov-2021",
        "completionDate": "",
        "partner": "",
        "client": "TDH Ecoland",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 136,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Long Phuoc 1/500",
        "country": "Vietnam",
        "location": "HCMC",
        "startDate": "30-Dec-2021",
        "completionDate": "",
        "partner": "",
        "client": "Intresco",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 16,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "Landscape Architecture and Urban Design",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Ben Tre Riverside",
        "country": "Vietnam",
        "location": "Ben Tre",
        "startDate": "8-Sep-2022",
        "completionDate": "",
        "partner": "",
        "client": "Sasaki",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 34.5,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Medical Park",
        "country": "Vietnam",
        "location": "HCMC",
        "startDate": "7-Jan-2022",
        "completionDate": "",
        "partner": "",
        "client": "Hoa Lam",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 783,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "South Phui",
        "country": "Vietnam",
        "location": "Quang Binh",
        "startDate": "29-Mar-2022",
        "completionDate": "",
        "partner": "",
        "client": "Dat Phuong",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": "",
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 15.923656,
        "lng": 108.129411,
        "projectName": "Dai Hiep Commune",
        "country": "Vietnam",
        "location": "Quang Nam",
        "startDate": "15-Apr-2022",
        "completionDate": "",
        "partner": "",
        "client": "Dat Phuong",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 99,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Thuy Thanh Eco - Hue",
        "country": "Vietnam",
        "location": "Hue",
        "startDate": "5-Apr-2022",
        "completionDate": "",
        "partner": "",
        "client": "Hoa Phat",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 29,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Logistics Zone - Kim Thanh",
        "country": "Vietnam",
        "location": "Lao Cai",
        "startDate": "25-Apr-2022",
        "completionDate": "",
        "partner": "",
        "client": "T&T",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 359,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "Business Park/High-tech Park/Industrial Park Planning",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Thuy Phuong - Hue",
        "country": "Vietnam",
        "location": "Hue",
        "startDate": "2-Jun-2022",
        "completionDate": "",
        "partner": "",
        "client": "Dat Phuong",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 323,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Ru Cha - Hue",
        "country": "Vietnam",
        "location": "Hue",
        "startDate": "2-Jun-2022",
        "completionDate": "",
        "partner": "",
        "client": "Dat Phuong",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 163,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 21.012534,
        "lng": 105.843805,
        "projectName": "Thong Nhat Park",
        "country": "Vietnam",
        "location": "Hanoi",
        "startDate": "18-May-2022",
        "completionDate": "",
        "partner": "",
        "client": "Thong Nhat Park",
        "clientType": "Government",
        "description": "",
        "projectValue": "",
        "projectScale": 205,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "Landscape Architecture and Urban Design",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Zone II Tourism Soc Son",
        "country": "Vietnam",
        "location": "Hanoi",
        "startDate": "30-Jun-2022",
        "completionDate": "",
        "partner": "",
        "client": "BRG",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": "",
        "status": "Completed",
        "sector1": "",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 12.804681,
        "lng": 108.23814,
        "projectName": "Dak Lak",
        "country": "Vietnam",
        "location": "Dak Lak",
        "startDate": "27-Jul-2022",
        "completionDate": "",
        "partner": "",
        "client": "Capital House",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 60,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 20.467981,
        "lng": 56.513824,
        "projectName": "Oman",
        "country": "Oman",
        "location": "Oman",
        "startDate": "14-Jul-2022",
        "completionDate": "",
        "partner": "",
        "client": "Meinhardt",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 158,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "Water & climate change",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Tra Giang",
        "country": "Vietnam",
        "location": "Thai Binh",
        "startDate": "12-Aug-2022",
        "completionDate": "",
        "partner": "",
        "client": "T&T",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": "",
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Xuan Thien Port Planning",
        "country": "Vietnam",
        "location": "Nam Dinh",
        "startDate": "12-Sep-2022",
        "completionDate": "",
        "partner": "",
        "client": "Xuan Thien",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 40000,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "Business Park/High-tech Park/Industrial Park Planning",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Cu Chi Social Housing",
        "country": "Vietnam",
        "location": "HCMC",
        "startDate": "8-Sep-2022",
        "completionDate": "",
        "partner": "",
        "client": "Phu Long",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": "",
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 15.602951,
        "lng": 108.034735,
        "projectName": "Quang Nam Gateway",
        "country": "Vietnam",
        "location": "Quang Nam",
        "startDate": "5-Dec-2022",
        "completionDate": "",
        "partner": "",
        "client": "Dat Phuong",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 104,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "Landscape Architecture and Urban Design",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 21.34012,
        "lng": 105.377255,
        "projectName": "Viet Tri City Master planning",
        "country": "Vietnam",
        "location": "Phu Tho",
        "startDate": "1-Sep-2022",
        "completionDate": "",
        "partner": "",
        "client": "Sunny World",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 0.19,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Tam Xa Ecological Smart City",
        "country": "Vietnam",
        "location": "Hanoi",
        "startDate": "10-Jun-2022",
        "completionDate": "",
        "partner": "",
        "client": "Xuan Cau",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 20000,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Youth Community engagement competition",
        "country": "Vietnam",
        "location": "Vietnam",
        "startDate": "20-Sep-2022",
        "completionDate": "",
        "partner": "",
        "client": "US Consulate",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 318,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "Water & climate change",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 11.570261,
        "lng": 107.816358,
        "projectName": "Nam Phuong Lake",
        "country": "Vietnam",
        "location": "Lam Dong",
        "startDate": "6-Oct-2022",
        "completionDate": "",
        "partner": "",
        "client": "TDH Ecoland",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": "",
        "status": "Completed",
        "sector1": "Other",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Huong Thuy township",
        "country": "Vietnam",
        "location": "Hue",
        "startDate": "24-Nov-2022",
        "completionDate": "",
        "partner": "",
        "client": "TNT",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 610,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Lim Chu Kang Competition",
        "country": "Singapore",
        "location": "Singapore",
        "startDate": "1-Jun-2022",
        "completionDate": "",
        "partner": "",
        "client": "Meinhardt",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 50,
        "status": "Completed",
        "sector1": "Urban Planning",
        "sector2": "competition",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Thu Duc City Master Plan",
        "country": "Vietnam",
        "location": "HCMC",
        "startDate": "21-Nov-2022",
        "completionDate": "",
        "partner": "",
        "client": "Thu Duc PPC",
        "clientType": "Government",
        "description": "",
        "projectValue": "",
        "projectScale": "",
        "status": "",
        "sector1": "Urban Planning",
        "sector2": "City Master Planning",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Revision of Binh Duong New City (BDNC) Master Plan",
        "country": "Vietnam",
        "location": "Binh Duong",
        "startDate": "2023",
        "completionDate": "",
        "partner": "",
        "client": "Becamex",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 230,
        "status": "",
        "sector1": "Urban Planning",
        "sector2": "Business Park/High-tech Park/Industrial Park Planning",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Pleiku Eco-Township",
        "country": "Vietnam",
        "location": "Gia Lai",
        "startDate": "2023",
        "completionDate": "",
        "partner": "",
        "client": "Hồng Phong",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": "",
        "status": "",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": -6.196445,
        "lng": 106.823572,
        "projectName": "Jakarta 2045",
        "country": "Vietnam",
        "location": "Jakarta",
        "startDate": "2023",
        "completionDate": "",
        "partner": "",
        "client": "West Java",
        "clientType": "Government",
        "description": "",
        "projectValue": "",
        "projectScale": 0.15,
        "status": "",
        "sector1": "",
        "sector2": "Research",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Park CX1 - North Luong Beo community Binh Tan",
        "country": "Vietnam",
        "location": "HCMC",
        "startDate": "2023",
        "completionDate": "",
        "partner": "",
        "client": "Binh Tan District Authority",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 686,
        "status": "",
        "sector1": "Urban Planning",
        "sector2": "Landscape Architecture and Urban Design",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Hong Phong - NORTH NINH BINH",
        "country": "Vietnam",
        "location": "Ninh Binh",
        "startDate": "2023",
        "completionDate": "",
        "partner": "",
        "client": "HONG PHONG (TDH)",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": "",
        "status": "",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Regional planning - Northern Midlands and Mountains",
        "country": "Vietnam",
        "location": "Northern Midlands and Mountains of Vietnam",
        "startDate": "2023",
        "completionDate": "",
        "partner": "",
        "client": "Ministry of planning and investment (Vietnam)",
        "clientType": "Government",
        "description": "",
        "projectValue": "",
        "projectScale": 687,
        "status": "",
        "sector1": "Regional and Provincial Planning",
        "sector2": "Regional and Provincial Planning",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Hong Phong - Con Noi - Ninh Binh",
        "country": "Vietnam",
        "location": "Ninh Binh",
        "startDate": "2023",
        "completionDate": "",
        "partner": "",
        "client": "HONG PHONG (TDH)",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": "",
        "status": "",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Medical Park- Detention pond (wellness park)",
        "country": "Vietnam",
        "location": "HCMC",
        "startDate": "2023",
        "completionDate": "",
        "partner": "",
        "client": "HOA LAM",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": 128,
        "status": "",
        "sector1": "Infrastructure Planning/Design",
        "sector2": "Landscape Architecture and Urban Design",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Hong Phong - Non Nuoc - Canh Dieu_ Prelim 1/2000",
        "country": "Vietnam",
        "location": "Ninh Binh",
        "startDate": "2023",
        "completionDate": "",
        "partner": "",
        "client": "HONG PHONG (TDH)",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": "300-meter long",
        "status": "",
        "sector1": "Urban Planning",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": "",
        "lng": "",
        "projectName": "Tay Ninh Industrial park",
        "country": "Vietnam",
        "location": "Becamex",
        "startDate": "2023",
        "completionDate": "",
        "partner": "",
        "client": "Becamex",
        "clientType": "Private",
        "description": "",
        "projectValue": "",
        "projectScale": "",
        "status": "",
        "sector1": "Industrial Planning",
        "sector2": "Business Park/High-tech Park/Industrial Park Planning",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    }
];

// Add more Project data rows as needed